version: "3.5"

services:
  db:
    image: postgres:12.2-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
