export enum languages{
    Typescript = "Typescript",
    Rust = "Rust",
    CSharp = "C#",
    TSX = "TSX",
    JavaScript = "JavaScript",
    JSX = "JSX",
    Python = "Python",
    Java = "Java",
    Lua = "Lua",
    R  = "R",
    C ="C",
    CPlusPlus = "C++",
    ObjectiveC = "Objective-C",
    Swift = "Swift",
    HTML = "HTML",
    CSS = "CSS",
    Sass = "Sass",
    Less = "Less",
    Dart = "Dart",
    Ruby = "Ruby",
}